export interface Tithi {
  id: number;
  name: string;
  nameNe: string;
  shortName: string;
  shortNameNe: string;
  isSpecial: boolean;
  fasting: boolean;
  avoidNonVeg: boolean;
  description: string;
  descriptionNe: string;
}

export interface Nakshatra {
  id: number;
  name: string;
  nameNe: string;
  shortName: string;
  shortNameNe: string;
  deity: string;
  deityNe: string;
}

export interface Paksha {
  id: number;
  name: string;
  nameNe: string;
  shortName: string;
  shortNameNe: string;
}

export const PAKSHAS: Paksha[] = [
  {
    id: 1,
    name: "Shukla",
    nameNe: "शुक्ल",
    shortName: "Shukla",
    shortNameNe: "शुक्ल",
  },
  {
    id: 2,
    name: "Krishna",
    nameNe: "कृष्ण",
    shortName: "Krishna",
    shortNameNe: "कृष्ण",
  },
];

export const TITHIS: Tithi[] = [
  {
    id: 1,
    name: "Pratipada",
    nameNe: "प्रतिपदा",
    shortName: "Pratipada",
    shortNameNe: "प्रतिपदा",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "First day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको पहिलो दिन",
  },
  {
    id: 2,
    name: "Dwitiya",
    nameNe: "द्वितीया",
    shortName: "Dwitiya",
    shortNameNe: "द्वितीया",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Second day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको दोस्रो दिन",
  },
  {
    id: 3,
    name: "Tritiya",
    nameNe: "तृतीया",
    shortName: "Tritiya",
    shortNameNe: "तृतीया",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Third day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको तेस्रो दिन",
  },
  {
    id: 4,
    name: "Chaturthi",
    nameNe: "चतुर्थी",
    shortName: "Chaturthi",
    shortNameNe: "चतुर्थी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Fourth day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको चौथो दिन",
  },
  {
    id: 5,
    name: "Panchami",
    nameNe: "पञ्चमी",
    shortName: "Panchami",
    shortNameNe: "पञ्चमी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Fifth day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको पाँचौं दिन",
  },
  {
    id: 6,
    name: "Shashthi",
    nameNe: "षष्ठी",
    shortName: "Shashthi",
    shortNameNe: "षष्ठी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Sixth day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको छैठौं दिन",
  },
  {
    id: 7,
    name: "Saptami",
    nameNe: "सप्तमी",
    shortName: "Saptami",
    shortNameNe: "सप्तमी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Seventh day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको सातौं दिन",
  },
  {
    id: 8,
    name: "Ashtami",
    nameNe: "अष्टमी",
    shortName: "Ashtami",
    shortNameNe: "अष्टमी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Eighth day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको आठौं दिन",
  },
  {
    id: 9,
    name: "Navami",
    nameNe: "नवमी",
    shortName: "Navami",
    shortNameNe: "नवमी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Ninth day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको नवौं दिन",
  },
  {
    id: 10,
    name: "Dashami",
    nameNe: "दशमी",
    shortName: "Dashami",
    shortNameNe: "दशमी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Tenth day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको दसौं दिन",
  },
  {
    id: 11,
    name: "Ekadashi",
    nameNe: "एकादशी",
    shortName: "Ekadashi",
    shortNameNe: "एकादशी",
    isSpecial: true,
    fasting: true,
    avoidNonVeg: true,
    description: "Eleventh day of lunar fortnight - Fasting day",
    descriptionNe: "चन्द्र पक्षको एघारौं दिन - उपवास दिन",
  },
  {
    id: 12,
    name: "Dwadashi",
    nameNe: "द्वादशी",
    shortName: "Dwadashi",
    shortNameNe: "द्वादशी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Twelfth day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको बाह्रौं दिन",
  },
  {
    id: 13,
    name: "Trayodashi",
    nameNe: "त्रयोदशी",
    shortName: "Trayodashi",
    shortNameNe: "त्रयोदशी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Thirteenth day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको तेह्रौं दिन",
  },
  {
    id: 14,
    name: "Chaturdashi",
    nameNe: "चतुर्दशी",
    shortName: "Chaturdashi",
    shortNameNe: "चतुर्दशी",
    isSpecial: false,
    fasting: false,
    avoidNonVeg: false,
    description: "Fourteenth day of lunar fortnight",
    descriptionNe: "चन्द्र पक्षको चौधौं दिन",
  },
  {
    id: 15,
    name: "Purnima",
    nameNe: "पूर्णिमा",
    shortName: "Purnima",
    shortNameNe: "पूर्णिमा",
    isSpecial: true,
    fasting: false,
    avoidNonVeg: false,
    description: "Full moon day",
    descriptionNe: "पूर्णिमा दिन",
  },
  {
    id: 16,
    name: "Amavasya",
    nameNe: "अमावस्या",
    shortName: "Amavasya",
    shortNameNe: "अमावस्या",
    isSpecial: true,
    fasting: false,
    avoidNonVeg: false,
    description: "New moon day",
    descriptionNe: "अमावस्या दिन",
  },
];

export const NAKSHATRAS: Nakshatra[] = [
  {
    id: 1,
    name: "Ashwini",
    nameNe: "अश्विनी",
    shortName: "Ashwini",
    shortNameNe: "अश्विनी",
    deity: "Ashwini Kumaras",
    deityNe: "अश्विनी कुमारहरू",
  },
  {
    id: 2,
    name: "Bharani",
    nameNe: "भरणी",
    shortName: "Bharani",
    shortNameNe: "भरणी",
    deity: "Yama",
    deityNe: "यम",
  },
  {
    id: 3,
    name: "Krittika",
    nameNe: "कृत्तिका",
    shortName: "Krittika",
    shortNameNe: "कृत्तिका",
    deity: "Agni",
    deityNe: "अग्नि",
  },
  {
    id: 4,
    name: "Rohini",
    nameNe: "रोहिणी",
    shortName: "Rohini",
    shortNameNe: "रोहिणी",
    deity: "Brahma",
    deityNe: "ब्रह्मा",
  },
  {
    id: 5,
    name: "Mrigashira",
    nameNe: "मृगशिरा",
    shortName: "Mrigashira",
    shortNameNe: "मृगशिरा",
    deity: "Soma",
    deityNe: "सोम",
  },
  {
    id: 6,
    name: "Ardra",
    nameNe: "आर्द्रा",
    shortName: "Ardra",
    shortNameNe: "आर्द्रा",
    deity: "Rudra",
    deityNe: "रुद्र",
  },
  {
    id: 7,
    name: "Punarvasu",
    nameNe: "पुनर्वसु",
    shortName: "Punarvasu",
    shortNameNe: "पुनर्वसु",
    deity: "Aditi",
    deityNe: "अदिति",
  },
  {
    id: 8,
    name: "Pushya",
    nameNe: "पुष्य",
    shortName: "Pushya",
    shortNameNe: "पुष्य",
    deity: "Brihaspati",
    deityNe: "बृहस्पति",
  },
  {
    id: 9,
    name: "Ashlesha",
    nameNe: "आश्लेषा",
    shortName: "Ashlesha",
    shortNameNe: "आश्लेषा",
    deity: "Nagas",
    deityNe: "नागहरू",
  },
  {
    id: 10,
    name: "Magha",
    nameNe: "मघा",
    shortName: "Magha",
    shortNameNe: "मघा",
    deity: "Pitris",
    deityNe: "पितृहरू",
  },
  {
    id: 11,
    name: "Purva Phalguni",
    nameNe: "पूर्व फाल्गुनी",
    shortName: "Purva Phalguni",
    shortNameNe: "पूर्व फाल्गुनी",
    deity: "Bhaga",
    deityNe: "भग",
  },
  {
    id: 12,
    name: "Uttara Phalguni",
    nameNe: "उत्तर फाल्गुनी",
    shortName: "Uttara Phalguni",
    shortNameNe: "उत्तर फाल्गुनी",
    deity: "Aryaman",
    deityNe: "अर्यमन्",
  },
  {
    id: 13,
    name: "Hasta",
    nameNe: "हस्त",
    shortName: "Hasta",
    shortNameNe: "हस्त",
    deity: "Savitar",
    deityNe: "सवितृ",
  },
  {
    id: 14,
    name: "Chitra",
    nameNe: "चित्रा",
    shortName: "Chitra",
    shortNameNe: "चित्रा",
    deity: "Vishvakarma",
    deityNe: "विश्वकर्मा",
  },
  {
    id: 15,
    name: "Swati",
    nameNe: "स्वाति",
    shortName: "Swati",
    shortNameNe: "स्वाति",
    deity: "Vayu",
    deityNe: "वायु",
  },
  {
    id: 16,
    name: "Vishakha",
    nameNe: "विशाखा",
    shortName: "Vishakha",
    shortNameNe: "विशाखा",
    deity: "Indra and Agni",
    deityNe: "इन्द्र र अग्नि",
  },
  {
    id: 17,
    name: "Anuradha",
    nameNe: "अनुराधा",
    shortName: "Anuradha",
    shortNameNe: "अनुराधा",
    deity: "Mitra",
    deityNe: "मित्र",
  },
  {
    id: 18,
    name: "Jyestha",
    nameNe: "ज्येष्ठा",
    shortName: "Jyestha",
    shortNameNe: "ज्येष्ठा",
    deity: "Indra",
    deityNe: "इन्द्र",
  },
  {
    id: 19,
    name: "Mula",
    nameNe: "मूल",
    shortName: "Mula",
    shortNameNe: "मूल",
    deity: "Nirrti",
    deityNe: "निरृति",
  },
  {
    id: 20,
    name: "Purva Ashadha",
    nameNe: "पूर्वाषाढा",
    shortName: "Purva Ashadha",
    shortNameNe: "पूर्वाषाढा",
    deity: "Apas",
    deityNe: "अपस्",
  },
  {
    id: 21,
    name: "Uttara Ashadha",
    nameNe: "उत्तराषाढा",
    shortName: "Uttara Ashadha",
    shortNameNe: "उत्तराषाढा",
    deity: "Visvedevas",
    deityNe: "विश्वेदेवहरू",
  },
  {
    id: 22,
    name: "Shravana",
    nameNe: "श्रवण",
    shortName: "Shravana",
    shortNameNe: "श्रवण",
    deity: "Vishnu",
    deityNe: "विष्णु",
  },
  {
    id: 23,
    name: "Dhanishta",
    nameNe: "धनिष्ठा",
    shortName: "Dhanishta",
    shortNameNe: "धनिष्ठा",
    deity: "Vasus",
    deityNe: "वसुहरू",
  },
  {
    id: 24,
    name: "Shatabhisha",
    nameNe: "शतभिषा",
    shortName: "Shatabhisha",
    shortNameNe: "शतभिषा",
    deity: "Varuna",
    deityNe: "वरुण",
  },
  {
    id: 25,
    name: "Purva Bhadrapada",
    nameNe: "पूर्वभाद्रपद",
    shortName: "Purva Bhadrapada",
    shortNameNe: "पूर्वभाद्रपद",
    deity: "Aja Ekapada",
    deityNe: "अज एकपाद",
  },
  {
    id: 26,
    name: "Uttara Bhadrapada",
    nameNe: "उत्तरभाद्रपद",
    shortName: "Uttara Bhadrapada",
    shortNameNe: "उत्तरभाद्रपद",
    deity: "Ahir Budhnya",
    deityNe: "अहिर बुध्न्य",
  },
  {
    id: 27,
    name: "Revati",
    nameNe: "रेवती",
    shortName: "Revati",
    shortNameNe: "रेवती",
    deity: "Pushan",
    deityNe: "पूषन्",
  },
];

export const getTithiById = (id: number): Tithi | undefined => {
  return TITHIS.find((tithi) => tithi.id === id);
};

export const getNakshatraById = (id: number): Nakshatra | undefined => {
  return NAKSHATRAS.find((nakshatra) => nakshatra.id === id);
};

export const getPakshaById = (id: number): Paksha | undefined => {
  return PAKSHAS.find((paksha) => paksha.id === id);
};
